---
title: "A Note on Statistics Anxiety"
author: Dr. Igor Tkalec, Social Data Institute, UCL
date: 12/12/2022
format: html
title-block-banner: slika.jpg
editor: visual
---

Back in 2010 (I was a senior in high school), my friend, then a freshman computer science student called me up one evening asking if I want to join him on a "quest". Considering we have known each other our whole lives, I gladly accepted his invitation. Later that afternoon when we met up I noticed he was carrying a book, which raised some questions in my head. It turned out that the "quest" was about the book. Without much context and explanation, he somewhat excitedly said that the book must be gone. It must disappear from his life and mind in every possible form. And so it was, the book "magically" disappeared. On the way home, he provided some context -- the book was a statistics textbook and he had just passed his undergraduate statistics exam. Back then little did I know that this is a manifestation of what is called statistics anxiety, an omnipresent phenomena among university students.

Statistics anxiety was the main theme of recent Statistics Teaching Community of Practice seminar held at University College London. In this blog post, I provide a brief conceptual overview of statistics anxiety and reflect upon its remedies that were the focus of the discussion at the seminar. Nowadays, statistics anxiety gains momentum notably in the context of (social) data science and corresponding coding skills that have permeated all scientific fields and have become crucial components of business operations and, consequently, labour market demands.

Statistics anxiety entails negative emotional reaction to encountering statistics in any form of level including data collection, data modelling, interpretation of statistical analyses (Bradstreet 1996; Koh and Zawi 2014). It is situation-specific meaning that its symptoms and effects occur only in environments where statistics has increased significance (e.g., attending a statistics class at a university) (Onwuegbuzie 2000). The effects of statistics anxiety *inter alia* include frustration, fear of failure, depression, panic, non-optimal learning and mental anguish (Schacht and Stewart 1990; Milgram, Sroloff, and Rosenbaum 1988; Onwuegbuzie 2004). Naturally, statistics anxiety is linked to poor performance in statistics classes.

However, there are strategies that remedy statistics anxiety of students. Content-focused remedies concern materials used in classes -- e.g., usage of humorous cartoons in explaining statistical concepts (see Ziv 1988). Teacher-focused remedies such as immediacy (Williams 2010) and teacher rapport (Bradstreet 1996) emphasise individual role of a teacher in dealing with statistics anxiety. Class-focused remedies concern modifications in class organisation, structure and objectives. These *inter alia* include moving away from test and conventional exams toward project-focused assessments (Wilson 1999), using real-life examples in teaching (Zanakis and Valenzi 1997) and the use of technology in classes (Hollis 1997).

The latter -- the use of technology -- was the main discussion point at the Community of Practice event. In this context, technology is equivalent to using coding to perform statistical analyses. First, the audience observed that coding tends to significantly contribute to statistics anxiety among students. Second, due to over-emphasis on coding in statistics classes that derives from its desirability and consequent monetisation on the labour market, students struggle to understand that coding is an instrument for doing statistical analysis, rather than the essence of statistical reasoning. In other words, students are more concerned about producing an errorless code than in making sense of the actual output of generated by the code. This implies that an instrument (i.e., coding) gains relative importance over reasoning (i.e., interpretation of the output and learning from data). One can immediately notice a problematic nature of such observations. This links to another issue that came up in the discussion and concerns general tendency of students to start developing a project by thinking which method to use (i.e., the instrument) instead of starting from the problem/question definition that should precede, supersede and directly inform the method of analysis.

Remedies to coding-induced statistics anxiety that the audience "tested" in their classes are predominantly class-focused and include: introducing coding labs only half way through the course; splitting (instead of merging) lectures on statistical reasoning from coding labs; using point-interface visual tools to demonstrate statistical concepts prior (re)demonstrating them in a coding environment; distinguishing statistical reasoning from coding and discussing their interaction.

By all means coding is an important skill students should master to a certain degree, but it should not supersede statistical/data science reasoning. Therefore, especially in a teaching environment, it is arguably productive to treat coding as an instrument that enables us to "give life" and operationalise reasoning that derives from pre-defined problem problem/question.

Embracing the reasoning in teaching which arguably reduces coding-induced statistics anxiety, may stop students going on "quests" from the 1^st^ paragraph as soon as they "suffer through" their classes. In this context, teachers are seen as the difference makers.

In conclusion: do not code for the sake of coding, but for the sake of obtaining and, importantly, understanding the answer to a problem/question.

References:

Bradstreet, Thomas E. 1996. 'Teaching Introductory Statistics Courses so That Nonstatisticians Experience Statistical Reasoning'. *The American Statistician* 50 (1): 69--78.

Hollis, P. J. 1997. 'Ideas for Improving Statistics Education'. *International Journal of Mathematical Education in Science and Technology* 28 (4): 569--73. https://doi.org/10.1080/0020739970280411.

Koh, Denise, and Mohd Khairi Zawi. 2014. 'Statistics Anxiety among Postgraduate Students'. *International Education Studies* 7 (13): 166--74. https://doi.org/10.5539/ies.v7n13p166.

Milgram, Norman A., Barry Sroloff, and Michael Rosenbaum. 1988. 'The Procrastination of Everyday Life'. *Journal of Research in Personality* 22 (2): 197--212. https://doi.org/10.1016/0092-6566(88)90015-3.

Onwuegbuzie, Anthony J. 2000. 'Statistics Anxiety and the Role of Self-Perceptions'. *The Journal of Educational Research* 93 (5): 323--30. https://doi.org/10.1080/00220670009598724.

---------. 2004. 'Academic Procrastination and Statistics Anxiety'. *Assessment & Evaluation in Higher Education* 29 (1): 3--19. https://doi.org/10.1080/0260293042000160384.

Schacht, Steven, and Brad J. Stewart. 1990. 'What's Funny about Statistics? A Technique for Reducing Student Anxiety'. *Teaching Sociology* 18 (1): 52. https://doi.org/10.2307/1318231.

Williams, Amanda S. 2010. 'Statistics Anxiety and Instructor Immediacy'. *Journal of Statistics Education* 18 (2): 10. https://doi.org/10.1080/10691898.2010.11889495.

Wilson, Vicki A. 1999. 'Reducing Statistics Anxiety': In . Point Clear, Alabama US.

Zanakis, Stelios H., and Enzo R. Valenzi. 1997. 'Student Anxiety and Attitudes in Business Statistics'. *Journal of Education for Business* 73 (1): 10--16. https://doi.org/10.1080/08832329709601608.

Ziv, Avner. 1988. 'Teaching and Learning with Humor: Experiment and Replication'. *The Journal of Experimental Education* 57 (1): 5--15.
